baseurl = "/"
languageCode = "en-us"
title = "kottn.me"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"
hasCJKLanguage = true
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    github_edit = "https://github.com/kottn/mypage/tree/master/content/"
    footer = "(c) 2017 kottn | [Github](https://github.com/kottn) | [Twitter](https://twitter.com/kottn_jp)"

